on:
  slack_command_webhook:
    config:
      filter:
        command:
          $regex: translateBook
jobs:
    print:
        name: Print
        runs-on: ubuntu-latest
        steps:
          - name: Print Outputs
            env:
              name: ${{on.slack_command_webhook.outputs.name}}
            run: |
              echo book_name: $name
    build:
        runs-on: ubuntu-20.04

        steps:
          - name: "Checkout code"
            uses: actions/checkout@v3

          - name: Git clone private repo
            uses: actions/checkout@v2
            with:
              repository: devalgroup/landmark-to-cn
              ref: main
              token: ${{ secrets.PRIVATE_REPO_TOKEN }}
  
          - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
              python-version: "3.10"
              architecture: "x64"
            env:
              AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
  
          - name: Git clone public repo
            run: git clone https://github.com/yihong0618/bilingual_book_maker.git
  
          - name: Install requirements in public repo
            run: |
              cd bilingual_book_maker
              pip install -r requirements.txt
  
          - name: Run another Python script in private repo
            env:
                OPENAI_API_KEY: ${{ secrets.AOAI_GPT35_KEY }}
            run: |
                cd bilingual_book_maker
                python3 make_book.py --book_name ../../landmark-to-cn/The\ Old\ Curiosity\ Shop.epub --api_base 'https://opi-gpt3-jp.openai.azure.com/' --openai_key 9c0e95c020024cecbfca6cda18b0600e --deployment_id 'gpt-35-turbo-16k' --test --language zh-hans 
